### ISSUE TITLE
生产模式静态文件报错

### ISSUE THREAD

**Issue by Minxio** [CoderCharm/djangoBlog#3]
在settings.__init__.py文件中配置ENV = os.getenv('ENV', 'server')后启动项目，项目无法读取到static文件中的静态资源。但通过修改 settings.__init__.py文件生产模式下的DEBUG = True时可以正常读取。这是何问题呢？

**Comment by wxy2077** [comment]
> 项目无法读取到static文件中的静态资源

生产模式，django是不提供静态文件服务，可以使用nginx静态文件服务。可以参考django官网，[静态文件开发](https://docs.djangoproject.com/zh-hans/4.0/ref/contrib/staticfiles/#static-file-development-view)，[生产环境提供静态服务](https://docs.djangoproject.com/zh-hans/4.0/howto/static-files/deployment/#serving-static-files-in-production)

> 但通过修改 settings.init.py文件生产模式下的DEBUG = True时可以正常读取。这是何问题呢？

你这个就是手动改成了开发模式，肯定就能正常读取。

**Comment by Minxio** [comment]
感谢解惑，baidu得到了方法解决。

**Comment by wxy2077** [comment]
部署的话，你可以参考我的[nginx配置文件](https://github.com/wxy2077/djangoBlog/blob/master/deployment/nginx/nginx.conf)，django部署确实有点点麻烦。

**Comment by iCytus** [comment]
首先很感谢作者大大，这个网站真的很好看，很实用，但是我在部署生产环境遇到一个问题：
打开首页的时候，css等静态资源都可以正常访问到，点击文章进入详情页后，就有部分css文件出现请求错误。
首页：
```
Request URL: https://www.xxxx.com/static/css/all.css
Request Method: GET
Status Code: 200 OK (from disk cache)
Remote Address: 49.234.4.67:443
Referrer Policy: strict-origin-when-cross-origin
```
详情页（请求路径会多一个 `/article/` ）：
```
Request URL: https://www.xxxx.com/article/static/css/all.css
Request Method: GET
Status Code: 404 Not Found
Remote Address: 127.0.0.1:7890
Referrer Policy: strict-origin-when-cross-origin
```
nginx.conf中关于 静态资源的配置，大致都是照搬项目里的nginx配置
```
                location /static {
                    #alias   /home/ubuntu/pyWorks/djangoBlog/STATIC;
                    alias   /home/blog/STATIC;
                    # Set the static file cache expiration time to 30 days
                    expires  30d;
                }
```
请问，我该如何处理这种情况呢

**Comment by wxy2077** [comment]
谢谢你夸我博客好看 😂（说实话有丢丢不好用）

应该是详情页模版语法的问题，我不知道你详情页使用静态文件的语法怎么写的，可以贴一下代码吗？
比如 https://github.com/wxy2077/djangoBlog/blob/master/templates/base.html#L27

**Comment by iCytus** [comment]
> 谢谢你夸我博客好看 😂（说实话有丢丢不好用）
> 
> 应该是详情页模版语法的问题，我不知道你详情页使用静态文件的语法怎么写的，可以贴一下代码吗？ 比如 https://github.com/wxy2077/djangoBlog/blob/master/templates/base.html#L27

我找到问题原因了，我原本的 base.html 中是 `href="./static/css/all.css"`，改成 `href="/static/css/all.css"` 就可以了，非常感谢！

```
    <link rel="stylesheet" type="text/css" href="/static/css/all.css">
    <link rel="stylesheet" type="text/css" href="/static/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/animate.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/lightgallery.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/matery.css">
    <link rel="stylesheet" type="text/css" href="/static/css/my.css">
```
